language: go

go:
  - tip

services:
 -  docker

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get -v -d

script:
  - make sbuca coveralls docker-image docker-push
